config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :users do
        resources :expenses do
          get :summary, on: :collection
        end
      end
    end
  end
  resources :users do
    resources :expenses do
      get :summary, on: :collection
    end
  end
  get 'home/index'
  root to: "users#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :expenses
end

app/controllers/api/v1/expenses_controller.rb
module Api::V1
  class ExpensesController < ApplicationController
    before_action :set_expense, only: %i[ show ]
    skip_before_action :verify_authenticity_token

    # GET /expenses or /expenses.json
    def index
      @expenses = Expense.where(user: params[:user_id])
      render json: @expenses.as_json
    end

    # GET /expenses/1 or /expenses/1.json
    def show
      @expense = Expense.find(params[:id])
      render json: @expense.as_json
    end

    # POST /expenses or /expenses.json
    def create
      @expense = Expense.new(expense_params)

      if @expense.save
        render json: @expense.as_json
      else
        render json: @expense.errors, status: :unprocessable_entity
      end
    end

    def summary
      @total_expenses_amount = { total_expenses_amount: Expense.where(user: params[:user_id]).sum(:amount_in_pennies) }
      render json: @total_expenses_amount.as_json
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expense_params
      params.require(:expense).permit(:user_id, :amount_in_pennies)
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api::V1
  class UsersController < ApplicationController
    before_action :set_user, only: %i[ show ]

    # GET /users or /users.json
    def index
      @users = User.all
      render json: @users.as_json(only: [:name])
    end

    # GET /users/1 or /users/1.json
    def show
      @user = User.find(params[:id])
      render json: @user.as_json(only: [:name])
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {})
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[ show edit update destroy]

  # GET /expenses or /expenses.json
  def index
    @expenses = Expense.where(user: params[:user_id])
  end

  # GET /expenses/1 or /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses or /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to user_expenses_url, notice: "Expense was successfully created." }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to user_expense_url(@expense), notice: "Expense was successfully updated." }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy!

    respond_to do |format|
      format.html { redirect_to user_expenses_url(params[:user_id]), notice: "Expense was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # GET /expenses/summary
  def summary
    @total_expenses_amount = Expense.where(user: params[:user_id]).sum(:amount_in_pennies)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expense_params
      params.require(:expense).permit(:user_id, :amount_in_pennies)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>">
</div>

app/views/expenses/_form.html.erb
<%= form_for(@expense, url: user_expenses_path) do |form| %>
  <% if @expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% @expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :user_id, value: params[:user_id], style: 'display:none' %>
  <%= form.number_field :amount_in_pennies %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Show this expense", user_expense_path(params[:user_id], @expense) %> |
  <%= link_to "Back to expenses", user_expenses_path %>
</div>

app/views/expenses/index.html.erb
<% require_relative '../../components/expense/expense_component' %>
<p style="color: green"><%= notice %></p>

<h1>Expenses</h1>

<div id="expenses">
  <% @expenses.each do |expense| %>
    <%= render ExpenseComponent.new(id: expense.id, amount: expense.amount_in_pennies) %>
    <p>
      <%= link_to "Show this expense", user_expense_path(params[:user_id], expense) %>
    </p>
  <% end %>
</div>

<%= link_to "New expense", new_user_expense_path %>

<%= link_to "Summary", summary_user_expenses_path %>

<%= link_to "Back to users", users_path %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Back to expenses", user_expenses_path %>
</div>

app/views/expenses/show.html.erb
<% require_relative '../../components/expense/expense_component' %>

<p style="color: green"><%= notice %></p>

<%= render ExpenseComponent.new(id: @expense.id, amount: @expense.amount_in_pennies) %>

<div>
  <%= link_to "Edit this expense", edit_user_expense_path(params[:user_id], @expense) %> |
  <%= link_to "Back to expenses", user_expenses_path %>

  <%= button_to "Destroy this expense", user_expense_path(params[:user_id], @expense), method: :delete %>
</div>

app/views/expenses/summary.html.erb
<h1>Summary</h1>

<p> Total expenses </p>

<p> <%= @total_expenses_amount %></p>

<div>
  <%= link_to "Back to expenses", user_expenses_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GlobacapExpensesTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.text_field :name %>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<% require_relative '../../components/user/user_component' %>

<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render UserComponent.new(id: user.id, name: user.name) %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>
  <%= link_to "To expenses", user_expenses_path(@user) %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>